using System.Collections.Generic;

namespace Zappy.ZappyTaskEditor.Helper
{
    public static class EnglishToJapaneseHelper
    {

        internal static readonly Dictionary<string, string> EnglishToJapanese = new Dictionary<string, string>()
        {
            {"Loops Activities", "ループ活動" },
            {"Break Loop"  ,  "ループを破る"},
            {"For Each Loop End"  ,  "ループ活動"},
            {"For Each Loop Start"  ,  "各ループエンド"},
            {"For Loop End"  ,  "ループエンド用"},
            {"For Loop Start"  ,  "ループスタート用"},
            {"Loop End"  ,  "ループエンド"},
            {"SharePoint Activities"  ,  "シェアポイントの活動"},
            {"Create List"  ,  "リストを作成"},
            {"Create List Item"  ,  "リストアイテムを作成する"},
            {"Update List Item"  ,  "リスト項目の更新"},
            {"ElementPicker Activities"  ,  "要素選択アクティビティ"},
            {"Element Click"  ,  "要素クリック"},
            {"Element Exists?"  ,  "要素は存在しますか？"},
            {"Element Property Get"  ,  "要素プロパティ取得"},
            {"Element Value Get"  ,  "要素値取得"},
            {"Element Value Set"  ,  "要素値セット"},
            {"Global Key Press"  ,  "グローバルキープレス"},
            {"Global Mouse Click"  ,  "グローバルマウスクリック"},
            {"Word Activities"  ,  "ワードアクティビティ"},
            {"Change Word Formating"  ,  "ワードフォーマットを変更する"},
            {"Convert Word To Pdf File"  ,  "単語をPdfファイルに変換する"},
            {"Word String Replace"  ,  "ワード文字列置換"},
            {"Web Activities"  ,  "ウェブ活動"},
            {"Http Client"  ,  "HTTPクライアント"},
            {"Convert Html To Text"  ,  "HTMLをテキストに変換"},
            {"Validate Activities"  ,  "アクティビティを検証する"},
            {"Compare Data"  ,  "データを比較する"},
            {"Path Exists"  ,  "パスが存在する"},
            {"Verify Configuration"  ,  "設定を確認する"},
            {"Python Activities"  ,  "Pythonの活動"},
            {"Run Python Script"  ,  "Pythonスクリプトを実行する"},
            {"Credentials Activities"  ,  "資格情報アクティビティ"},
            {"Get Credentials"  ,  "資格を取得する"},
            {"Save Credentials"  ,  "資格情報を保存"},
            {"Picture Activities"  ,  "写真アクティビティ"},
            {"Cleanup Image"  ,  "クリーンアップ画像"},
            {"Scan Document"  ,  "文書をスキャン"},
            {"OCR Activities"  ,  "OCRの活動"},
            {"Ocr To Searchable PDF"  ,  "検索可能なPDFへのアクセス"},
            {"Google Image Ocr"  ,  "グーグルの画像 Ocr"},
            {"Microsoft Cloud OCR To Clipboard"  ,  "クリップボードにマイクロソフトクラウドOCR"},
            {"Ocr To Text"  ,  "テキストに対するOcr"},
            {"Ocr To Clipboard"  ,  "クリップボードへの変換"},
            {"Google Pdf To Text"  ,  "グーグル Pdf にテキスト"},
            {"Database Activities"  ,  "データベース活動"},
            {"Execute Non Query"  ,  "非クエリ実行"},
            {"Execute Query"  ,  "クエリ実行"},
            {"Insert Data Table"  ,  "データテーブルを挿入"},
            {"Get Data Table From Data Base"  ,  "データベースからデータテーブルを取得する"},
            {"Mail Activities"  ,  "メールアクティビティ"},
            {"Create Folder In Outlook"  ,  "フォルダを作成見通し"},
            {"Outlook Mail Search"  ,  "見通しメール検索"},
            {"Save Outlook Mail Attachment"  ,  "見通しメールの添付ファイルを保存する"},
            {"Read Outlook Mail"  ,  "見通しメールを読む"},
            {"Sort Inbox Outlook Mail"  ,  "受信トレイ見通しメールの並べ替え"},
            {"Outlook Mail Send"  ,  "見通しメール送信"},
            {"Outlook Read All Emails"  ,  "見通しすべてのEメールを読む"},
            {"SMTP Mail Send"  ,  "SMTPメール送信"},
            {"Triggers Activities"  ,  "活動をトリガーする"},
            {"Daily Timer Trigger"  ,  "デイリータイマートリガー"},
            {"File Change Trigger"  ,  "ファイル変更トリガ"},
            {"Folder Change Trigger"  ,  "フォルダ変更トリガ"},
            {"Fire Once Timer Trigger"  ,  "1回限りのタイマートリガー"},
            {"Global Update Trigger"  ,  "グローバル更新トリガー"},
            {"System Idle Trigger","システムIdleトリガー" },
            {"Outlook New Read Email Trigger"  ,  "見通しの新規開封済みメールトリガー"},
            {"Periodic Timer Trigger"  ,  "周期的タイマトリガ"},
            {"PDF Activities"  ,  "PDFの活動"},
            {"Enable Reading Protected PDF"  ,  "保護されたPDFの閲覧を有効にする"},
            {"Extract PDF Tables"  ,  "PDFテーブルの抽出"},
            {"Pdf Table Extraction Using Python"  ,  "Pythonを使用したPdfテーブルの抽出"},
            {"Merge Pdf"  ,  "Pdfをマージ"},
            {"PDF To Text"  ,  "テキストへのPDF"},
            {"PDF To Text Sharp"  ,  "テキストをシャープにPDF"},
            {"Miscellaneous Activities"  ,  "その他の活動"},
            {"Current Date And Time"  ,  "現在の日時"},
            {"Split Text"  ,  "分割テキスト"},
            {"Open File Dialog"  ,  "ファイルを開くダイアログ"},
            {"Remove Internet File Protection"  ,  "インターネットファイル保護を削除する"},
            {"Run CMD Scripts"  ,  "コマンドラインスクリプトを実行する"},
            {"Set State"  ,  "状態を設定"},
            {"Set Value"  ,  "設定値"},
            {"String Data Search"  ,  "文字列データ検索"},
            {"Convert Alphabet To Number"  ,  "アルファベットを数字に変換"},
            {"Convert Name Order Surname Last"  ,  "名前順姓の変換"},
            {"Input Box Multiple Values"  ,  "入力ボックスの複数の値"},
            {"Input CSV Val"  ,  "入力CSV値"},
            {"Input Box"  ,  "入力ボックス"},
            {"Message Box"  ,  "メッセージボックス"},
            {"Delay"  ,  "ディレイ"},
            {"Drag Drop"  ,  "ドラッグドロップ"},
            {"Marker"  ,  "マーカー"},
            {"Warning"  ,  "警告"},
            {"Error"  ,  "エラー"},
            {"Invoke"  ,  "呼び出す"},
            {"Media"  ,  "メディア"},
            {"System"  ,  "システム"},
            {"Touch"  ,  "タッチ"},
            {"Drag"  ,  "ドラッグ"},
            {"Beep"  ,  "ビープ"},
            {"Build Data Table"  ,  "データテーブル作成"},
            {"Clear Data Table"  ,  "クリアデータテーブル"},
            {"Get Processes"  ,  "プロセスを入手"},
            {"Get Html Content From Url"  ,  "URLからHTMLコンテンツを取得する"},
            {"Get Environment Folder"  ,  "環境フォルダの取得"},
            {"Get Environment Variable"  ,  "環境変数を取得"},
            {"Kill Process"  ,  "キルプロセス"},
            {"Merge Data Table"  ,  "データテーブルのマージ"},
            {"String Replace"  ,  "文字列置換"},
            {"MailExchange Activities"  ,  "メール交換活動"},
            {"Gets Exchange Mail From Inbox"  ,  "受信トレイから交換メールを取得する"},
            {"GoogleSpreadSheet Activities"  ,  "グーグルスプレッドシートの活動"},
            {"Delete Google Spread Sheet Entry"  ,  "グーグルスプレッドシートのエントリを削除する"},
            {"Get Spread Sheet Value"  ,  "スプレッドシートの値を取得する"},
            {"Set Range Google Spread Sheet"  ,  "範囲スプレッドシートグーグルスプレッドシート"},
            {"Set Value Google Spread Sheet"  ,  "設定値グーグルスプレッドシート"},
            {"Files Activities"  ,  "ファイルアクティビティ"},
            {"Latest Modified File Path"  ,  "最新の修正ファイルパス"},
            {"Get Files In Directory"  ,  "ディレクトリ内のファイルを取得する"},
            {"Compare Text?"  ,  "テキストを比較する"},
            {"File Open"  ,  "ファイルを開く"},
            {"Select Folder"  ,  "フォルダーを選択"},
            {"File Append Text"  ,  "ファイル追加テキスト"},
            {"File Copy"  ,  "ファイルコピー"},
            {"File Create"  ,  "ファイル作成"},
            {"File Delete"  ,  "ファイル削除"},
            {"File Exists?"  ,  "ファイルが存在しています？"},
            {"File Info Get"  ,  "ファイル情報取得"},
            {"File Move"  ,  "ファイル移動"},
            {"File Write Text"  ,  "ファイル書き込みテキスト"},
            {"Folder Create"  ,  "フォルダ作成"},
            {"Folder Delete"  ,  "フォルダ削除"},
            {"Folder Exists?"  ,  "フォルダが存在しますか？"},
            {"Folder Info Get"  ,  "フォルダ情報取得"},
            {"Folder Move"  ,  "フォルダ移動"},
            {"Excel Activities"  ,  "エクセルの活動"},
            {"Add Missing Column Values"  ,  "不足している列値を追加"},
            {"Delete Missing Column Values"  ,  "欠落している列の値を削除する"},
            {"CSV File To Excel"  ,  "CSVファイルからエクセル"},
            {"Excel Range Copy"  ,  "エクセル範囲コピー"},
            {"Excel Range Paste"  ,  "エクセルの範囲貼り付け"},
            {"Excel Sheet Auto Fit Columns"  ,  "エクセルシートの自動調整列"},
            {"Open Ca Data Entry Excel File"  ,  "Caデータ入力エクセルファイルを開く"},
            {"Excel Column Split"  ,  "エクセルの列分割"},
            {"Excel Column Values To Dict"  ,  "決定するエクセルの列値"},
            {"Get Excel Column Values Compare"  ,  "エクセルの列値を比較する"},
            {"Update Value Compare Excel Column Values"  ,  "値を更新するエクセルの列値を比較する"},
            {"Excel File To Data Set"  ,  "データセットへのエクセルファイル"},
            {"Excel Find Text"  ,  "エクセルのテキスト検索"},
            {"Excel Get Column Heading"  ,  "エクセルの列見出しの取得"},
            {"Excel Get Focused Cell"  ,  "エクセルはセルに焦点を当てる"},
            {"Excel Get Last Row Column"  ,  "エクセルの最後の行を取得列"},
            {"Excel Get Property"  ,  "エクセル物件取得"},
            {"Excel Set Focused Cell"  ,  "エクセル集束セルの設定"},
            {"Excel Set Property"  ,  "エクセルプロパティを設定"},
            {"Copied Excel Cells To Data Table"  ,  "データテーブルにコピーされたエクセルセル"},
            {"Excel Send Keys"  ,  "エクセル送信キー"},
            {"Macro Run"  ,  "マクロラン"},
            {"ExcelWorkbook Activities"  ,  "エクセルワークブックアクティビティ"},
            {"Workbook Close"  ,  "ワークブック閉じる"},
            {"Workbook Close All"  ,  "ワークブックすべて閉じる"},
            {"Workbook Count"  ,  "ワークブック数"},
            {"Workbook Create"  ,  "ワークブック作成"},
            {"Workbook Open"  ,  "ワークブックを開く"},
            {"Workbook Refresh All"  ,  "ワークブックリフレッシュすべて"},
            {"Workbook Save"  ,  "ワークブック保存"},
            {"Workbook Save As"  ,  "ワークブック名​​前を付けて保存"},
            {"Worksheet Count"  ,  "ワークシート数"},
            {"Worksheet Delete"  ,  "ワークシート削除"},
            {"Worksheet Exists?"  ,  "ワークシートは存在しますか？"},
            {"Worksheet Create"  ,  "ワークシート作成"},
            {"Documents Activities"  ,  "ドキュメント活動"},
            {"Text Normalization"  ,  "テキスト正規化"},
            {"Data Extraction"  ,  "データ抽出"},
            {"Nlp Map Entities"  ,  "Nlpマップエンティティ"},
            {"Read Text File"  ,  "テキストファイルを読む"},
            {"Write Text To File"  ,  "テキストをファイルに書き込む"},
            {"Core Activities"  ,  "中核業務"},
            {"VB Run Script"  ,  "VB実行スクリプト"},
            {"Value Increment"  ,  "値の増加"},
            {"Group"  ,  "グループ"},
            {"Run Zappy Task From File" , "ファイルからザッピータスクを実行する"},
            { "Global Update"  ,  "グローバルアップデート"},
            {"Run Zappy Task",  "ザッピータスクを実行する"},
            {"Pause"  ,  "一時停止"},
            {"App Start"  ,  "アプリ開始"},
            {"Run Script"  ,  "スクリプトを実行"},
            {"Decision?"  ,  "決定？"},
            {"End"  ,  "終わり"},
            {"Variable"  ,  "変数"},
            {"Code Activities"  ,  "コードアクティビティ"},
            {"Data Table Remove Empty Cells"  ,  "データテーブルの空のセルの削除"},
            {"Data Table Get Property"  ,  "データテーブル取得プロパティ"},
            {"Data Table Last Row Column"  ,  "データテーブル最終行列"},
            {"Data Table Send Keys"  ,  "データテーブル送信キー"},
            {"Data Table Set Property"  ,  "データテーブルセットプロパティ"},
            {"Set Variable Value"  ,  "変数値を設定"},
            {"Data Table To 2D Array"  ,  "2D配列へのデータテーブル"},
            {"String To String Array"  ,  "文字列から文字列への配列"},
            {"Data Table To Excel"  ,  "エクセルへのデータテーブル"},
            {"Excel To Data Table"  ,  "データテーブルへのエクセル"},
            {"String Array To Data Table"  ,  "データテーブルへの文字列配列"},
            {"String Array To String"  ,  "文字列配列から文字列へ"},
            {"String To Clipboard"  ,  "クリップボードへの文字列"},
            {"Clipboard To String"  ,  "文字列へのクリップボード"},
            {"CSV To Data Table"  ,  "CSVからデータテーブルへ"},
            {"Data Table To CSV File"  ,  "CSVファイルへのデータテーブル"},
            {"Citrix Activities"  ,  "Citrixの活動"},
            {"Focus Window Type"  ,  "フォーカスウィンドウタイプ"},
            {"Image Click"  ,  "画像クリック"},
            {"Image Double Click"  ,  "画像ダブルクリック"},
            {"Image Right Click"  ,  "画像右クリック"},
            {"Chrome Activities"  ,  "クロムのアクティビティ"},
            {"Chrome Get HTML Content"  ,  "クロムでHTMLコンテンツを取得する"},
            {"Chrome Mouse"  ,  "クロムマウス"},
            {"Chrome fire Event"  , "クロム火災イベント"},
            {"Chrome Keyboard"  ,  "クロムキーボード"},
            {"Chrome Miscellaneous"  ,  "クロムその他"},
            {"Chrome click At"  ,  "クロムAtをクリック"},
            {"Chrome drag And Drop To Object"  ,  "クロムでオブジェクトにドラッグアンドドロップ"},
            {"Chrome edit Content"  ,  "クロム編集コンテンツ"},
            {"Chrome open"  ,  "クロムを開く"},
            {"Chrome run Script"  ,  "クロム実行スクリプト"},
            {"Chrome select"  ,  "クロムセレクト"},
            {"Chrome select Frame" , "クロムフレームを選択"},
            {"Chrome send Keys"  ,  "クロム送信キー"},
            {"Chrome submit"  ,  "クロム送信"},
            {"Chrome type"  ,  "クロームタイプ"},
            {"Chrome"  ,  "クロム"},
            {"Mouse Activities"  ,  "マウスの活動"},
            {"Mouse"  ,  "マウス"},
            {"Keyboard Activities"  ,  "キーボードアクティビティ"},
            {"Send Keys"  ,  "キーを送る"},
            {"Activities"  ,  "アクティビティ"},
            { "Start" , "開始" },
            { "WorkSpace" , "作業スペース"},
            {"Focused Window Type","フォーカスウィンドウタイプ"},
            {"Aws Textrat Helper","AWS Textratヘルパー" },
            {"Type","タイプ" },
            {"Action","アクション" },
            {"String","ひも" }
        };

    }
}