using System.Collections.Generic;

namespace Zappy.ZappyTaskEditor.Helper
{
    class EnglishToPolishHelper
    {
        internal static readonly Dictionary<string, string> EnglishToPolish = new Dictionary<string, string>()
        {
            {"Loops Activities", "aktywności Pętle" },
            {"Break Loop"  ,  "Przerwij pętlę"},
            {"For Each Loop End"  ,  "Dla każdego końca pętli"},
            {"For Each Loop Start"  ,  "Dla każdej pętli Start"},
            {"For Loop End"  ,  "Na koniec pętli"},
            {"For Loop Start"  ,  "Na początek pętli"},
            {"Loop End"  ,  "Koniec pętli"},
            {"SharePoint Activities"  ,  "Działania SharePoint"},
            {"Create List"  ,  "Sporządzać listę"},
            {"Create List Item"  ,  "Utwórz element listy"},
            {"Update List Item"  ,  "Zaktualizuj element listy"},
            {"ElementPicker Activities"  ,  "Działania ElementPicker"},
            {"Element Click"  ,  "Kliknij element"},
            {"Element Exists?"  ,  "Czy istnieje element?"},
            {"Element Property Get"  ,  "Pobierz element własności"},
            {"Element Value Get"  ,  "Uzyskaj wartość elementu"},
            {"Element Value Set"  ,  "Zestaw wartości lementu"},
            {"Global Key Press"  ,  "Naciśnij klawisz globalny"},
            {"Global Mouse Click"  ,  "Globalne kliknięcie myszą"},
            {"Word Activities"  ,  "Działania na słowa"},
            {"Change Word Formating"  ,  "Zmień formowanie słów"},
            {"Convert Word To Pdf File"  ,  "Konwertuj słowo do pliku PDF"},
            {"Word String Replace"  ,  "Zamień ciąg słów"},
            {"Web Activities"  ,  "Działania w sieci"},
            {"Http Client"  ,  "Klient HTTP"},
            {"Convert Html To Text"  ,  "Konwertuj HTML na tekst"},
            {"Validate Activities"  ,  "Zatwierdź działania"},
            {"Compare Data"  ,  "Porównaj dane"},
            {"Path Exists"  ,  "Ścieżka istnieje"},
            {"Verify Configuration"  ,  "Sprawdź konfigurację"},
            {"Python Activities"  ,  "Działania w Pythonie"},
            {"Run Python Script"  ,  "Uruchom skrypt Pythona"},
            {"Credentials Activities"  ,  "Działania poświadczające"},
            {"Get Credentials"  ,  "Uzyskaj poświadczenia"},
            {"Save Credentials"  ,  "Zapisz poświadczenia"},
            {"Picture Activities"  ,  "Aktywności obrazkowe"},
            {"Cleanup Image"  ,  "Oczyść obraz"},
            {"Scan Document"  ,  "Skanuj dokument"},
            {"OCR Activities"  ,  "Działania OCR"},
            {"Ocr To Searchable PDF"  ,  "Ocr Do przeszukiwalnego pliku PDF"},
            {"Google Image Ocr"  ,  "Google Image Ocr"},
            {"Microsoft Cloud OCR To Clipboard"  ,  "Microsoft Cloud OCR do schowka"},
            {"Ocr To Text"  ,  "ocr do tekstu"},
            {"Ocr To Clipboard"  ,  "Ocr do schowka"},
            {"Google Pdf To Text"  ,  "Google PDF do tekstu"},
            {"Database Activities"  ,  "Działalność bazy danych"},
            {"Execute Non Query"  ,  "Wykonaj zapytanie bez zapytania"},
            {"Execute Query"  ,  "Wykonaj zapytanie"},
            {"Insert Data Table"  ,  "Wstaw tabelę danych"},
            {"Get Data Table From Data Base"  ,  "Uzyskaj tabelę danych z bazy danych"},
            {"Mail Activities"  ,  "Działania pocztowe"},
            {"Create Folder In Outlook"  ,  "Utwórz folder w programie Outlook"},
            {"Outlook Mail Search"  ,  "Wyszukiwanie poczty Outlook"},
            {"Save Outlook Mail Attachment"  ,  "Zapisz załącznik poczty programu Outlook"},
            {"Read Outlook Mail"  ,  "Czytaj pocztę programu Outlook"},
            {"Sort Inbox Outlook Mail"  ,  "Sortuj Inbox Outlook Mail"},
            {"Outlook Mail Send"  ,  "Outlook Mail Send"},
            {"Outlook Read All Emails"  ,  "Outlook Przeczytaj wszystkie wiadomości e-mail"},
            {"SMTP Mail Send"  ,  "Wysyłanie poczty SMTP"},
            {"Triggers Activities"  ,  "Czynności wyzwalające"},
            {"Daily Timer Trigger"  ,  "Wyzwalacz dzienny"},
            {"File Change Trigger"  ,  "Wyzwalacz zmiany pliku"},
            {"Folder Change Trigger"  ,  "Wyzwalacz zmiany folderu"},
            {"Fire Once Timer Trigger"  ,  "Wyzwalacz czasowy ognia raz"},
            {"Global Update Trigger"  ,  "Wyzwalacz aktualizacji globalnej"},
            {"Outlook New Read Email Trigger"  ,  "Wyzwalacz nowej wiadomości e-mail w programie Outlook"},
            {"Periodic Timer Trigger"  ,  "Okresowy wyzwalacz czasowy"},
            {"PDF Activities"  ,  "Działania w formacie PDF"},
            {"Enable Reading Protected PDF"  ,  "Włącz PDF chroniony przed czytaniem"},
            {"Extract PDF Tables"  ,  "Wyodrębnij tabele PDF"},
            {"Pdf Table Extraction Using Python"  ,  "Ekstrakcja tabeli PDF przy użyciu Pythona"},
            {"Merge Pdf"  ,  "Połącz pliki PDF"},
            {"PDF To Text"  ,  "PDF do tekstu"},
            {"PDF To Text Sharp"  ,  "Ostry plik PDF do tekstu"},
            {"Miscellaneous Activities"  ,  "Różne działania"},
            {"Current Date And Time"  ,  "Bieżąca data i godzina"},
            {"Split Text"  ,  "Podziel tekst"},
            {"Open File Dialog"  ,  "Otwórz okno dialogowe pliku"},
            {"Remove Internet File Protection"  ,  "Usuń ochronę plików internetowych"},
            {"Run CMD Scripts"  ,  "Uruchom skrypty CMD"},
            {"Set State"  ,  "Ustaw stan"},
            {"Set Value"  ,  "Ustalić wartość"},
            {"String Data Search"  ,  "Wyszukiwanie danych ciągów"},
            {"Convert Alphabet To Number"  ,  "Konwertuj alfabet na liczbę"},
            {"Convert Name Order Surname Last"  ,  "Konwertuj Nazwa Zamówienie Nazwisko Ostatnie"},
            {"Input Box Multiple Values"  ,  "Pole wejściowe Wiele wartości"},
            {"Input CSV Val"  ,  "Wprowadź CSV Val"},
            {"Input Box"  ,  "Pole wprowadzania"},
            {"Message Box"  ,  "Skrzynka pocztowa"},
            {"Delay"  ,  "Opóźnienie"},
            {"Drag Drop"  ,  "Drag Drop"},
            {"Marker"  ,  "Znacznik"},
            {"Warning"  ,  "Ostrzeżenie"},
            {"Error"  ,  "Błąd"},
            {"Invoke"  ,  "Odwołać się"},
            {"Media"  ,  "Głoska bezdźwięczna"},
            {"System"  ,  "System"},
            {"Touch"  ,  "Dotknąć"},
            {"Drag"  ,  "Opór"},
            {"Beep"  ,  "Brzęczyk"},
            {"Build Data Table"  ,  "Utwórz tabelę danych"},
            {"Clear Data Table"  ,  "Wyczyść tabelę danych"},
            {"Get Processes"  ,  "Uzyskaj procesy"},
            {"Get Html Content From Url"  ,  "Pobierz zawartość HTML z adresu URL"},
            {"Get Environment Folder"  ,  "Pobierz folder środowiska"},
            {"Get Environment Variable"  ,  "Uzyskaj zmienną środowiskową"},
            {"Kill Process"  ,  "Zamknij proces"},
            {"Merge Data Table"  ,  "Scal tabelę danych"},
            {"String Replace"  ,  "String Replace"},
            {"MailExchange Activities"  ,  "Działania MailExchange"},
            {"Gets Exchange Mail From Inbox"  ,  "Pobiera Exchange Mail From Inbox"},
            {"GoogleSpreadSheet Activities"  ,  "Działania GoogleSpreadSheet"},
            {"Delete Google Spread Sheet Entry"  ,  "Usuń wpis Google SpreadSheet"},
            {"Get Spread Sheet Value"  ,  "Uzyskaj wartość arkusza kalkulacyjnego"},
            {"Set Range Google Spread Sheet"  ,  "Ustaw arkusz Google Spread Range"},
            {"Set Value Google Spread Sheet"  ,  "Ustaw arkusz wartości Google"},
            { "Files Activities"  ,  "Aktywności plików"},
            {"Latest Modified File Path"  ,  "Najnowsza zmodyfikowana ścieżka do pliku"},
            {"Get Files In Directory"  ,  "Pobierz pliki w katalogu"},
            {"Compare Text?"  ,  "Porównaj tekst?"},
            {"File Open"  ,  "Plik otwarty"},
            {"Select Folder"  ,  "Wybierz katalog"},
            {"File Append Text"  ,  "Plik dołącz tekst"},
            {"File Copy"  ,  "Kopiuj plik"},
            {"File Create"  ,  "Utwórz plik"},
            {"File Delete"  ,  "Usuń plik"},
            {"File Exists?"  ,  "Plik istnieje?"},
            { "File Info Get"  ,  "Informacje o pliku Pobierz"},
            {"File Move"  ,  "Przenieś plik"},
            {"File Write Text"  ,  "Plik Napisz tekst"},
            {"Folder Create"  ,  "Utwórz folder"},
            {"Folder Delete"  ,  "Usuń folder"},
            {"Folder Exists?"  ,  "Czy istnieje folder?"},
            {"Folder Info Get"  ,  "Informacje o folderze Pobierz"},
            {"Folder Move"  ,  "Przenieś folder"},
            {"Excel Activities"  ,  "Działania programu Excel"},
            {"Add Missing Column Values"  ,  "Dodaj brakujące wartości kolumn"},
            {"Delete Missing Column Values"  ,  "Usuń brakujące wartości kolumn"},
            {"CSV File To Excel"  ,  "Plik CSV do programu Excel"},
            {"Excel Range Copy"  ,  "Kopia zakresu programu Excel"},
            {"Excel Range Paste"  ,  "Wklej zakres Excel"},
            {"Excel Sheet Auto Fit Columns"  ,  "Kolumny automatycznego dopasowania arkusza Excel"},
            {"Open Ca Data Entry Excel File"  ,  "Otwórz plik Excel Data Entry"},
            {"Excel Column Split"  ,  "Podziel kolumnę Excel"},
            {"Excel Column Values To Dict"  ,  "Wartości kolumn w programie Excel do dyktowania"},
            {"Get Excel Column Values Compare"  ,  "Porównaj wartości kolumn w programie Excel"},
            {"Update Value Compare Excel Column Values"  ,  "Aktualizuj wartość Porównaj wartości kolumn programu Excel"},
            {"Excel File To Data Set"  ,  "Plik Excel do zestawu danych"},
            {"Excel Find Text"  ,  "Znajdź tekst w Excelu"},
            {"Excel Get Column Heading"  ,  "Excel Uzyskaj nagłówek kolumny"},
            {"Excel Get Focused Cell"  ,  "Excel Get Focused Cell"},
            {"Excel Get Last Row Column"  ,  "Excel Uzyskaj ostatnią kolumnę wiersza"},
            {"Excel Get Property"  ,  "Excel Pobierz nieruchomość"},
            {"Excel Set Focused Cell"  ,  "Excel Set Focused Cell"},
            {"Excel Set Property"  ,  "Właściwość zestawu Excel"},
            {"Copied Excel Cells To Data Table"  ,  "Skopiowane komórki Excel do tabeli danych"},
            {"Excel Send Keys"  ,  "Excel Wyślij klucze"},
            {"Macro Run"  ,  "Uruchom makro"},
            {"ExcelWorkbook Activities"  ,  "ExcelWorkbook Activities"},
            {"Workbook Close"  ,  "Zamknij skoroszyt"},
            {"Workbook Close All"  ,  "Skoroszyt Zamknij wszystko"},
            {"Workbook Count"  ,  "Liczba skoroszytów"},
            {"Workbook Create"  ,  "Tworzenie skoroszytu"},
            {"Workbook Open"  ,  "Skoroszyt otwarty"},
            {"Workbook Refresh All"  ,  "Odśwież skoroszyt Wszystkie"},
            {"Workbook Save"  ,  "Zapisz skoroszyt"},
            {"Workbook Save As"  ,  "Skoroszyt Zapisz jako"},
            {"Worksheet Count"  ,  "Licznik arkuszy"},
            {"Worksheet Delete"  ,  "Arkusz roboczy Usuń"},
            {"Worksheet Exists?"  ,  "Arkusz roboczy istnieje？"},
            {"Worksheet Create"  ,  "Arkusz roboczy Utwórz"},
            {"Documents Activities"  ,  "Działania dotyczące dokumentów"},
            {"Text Normalization"  ,  "Normalizacja tekstu"},
            {"Data Extraction"  ,  "Ekstrakcja danych"},
            {"Nlp Map Entities"  ,  "Nlp Map Entities"},
            {"Read Text File"  ,  "Czytaj plik tekstowy"},
            {"Write Text To File"  ,  "Napisz tekst do pliku"},
            {"Core Activities"  ,  "Główne działania"},
            {"VB Run Script"  ,  "VB Run Script"},
            {"Value Increment"  ,  "Przyrost wartości"},
            {"Group"  ,  "Grupa"},
            {"Run Zappy Task From File" , "Uruchom Zappy Task From File"},
            { "Global Update"  ,  "Globalna aktualizacja"},
            {"Run Zappy Task",  "Uruchom zadanie Zappy"},
            {"Pause"  ,  "Pauza"},
            {"App Start"  ,  "Start aplikacji"},
            {"Run Script"  ,  "Uruchom skrypt"},
            {"Decision?"  ,  "Decyzja？"},
            {"End"  ,  "Koniec"},
            {"Variable"  ,  "Zmienna"},
            {"Code Activities"  ,  "Code Activities"},
            {"Data Table Remove Empty Cells"  ,  "Tabela danych Usuń puste komórki"},
            {"Data Table Get Property"  ,  "Tabela danych Pobierz właściwość"},
            {"Data Table Last Row Column"  ,  "Tabela danych Ostatnia kolumna wiersza"},
            {"Data Table Send Keys"  ,  "Klucze wysyłania tabeli danych"},
            {"Data Table Set Property"  ,  "Właściwość Zestaw tabel danych"},
            {"Set Variable Value"  ,  "Ustaw wartość zmiennej"},
            {"Data Table To 2D Array"  ,  "Tabela danych do macierzy 2D"},
            {"String To String Array"  ,  "Tablica ciąg-łańcuch"},
            {"Data Table To Excel"  ,  "Tabela danych do programu Excel"},
            {"Excel To Data Table"  ,  "Tabela Excel do danych"},
            {"String Array To Data Table"  ,  "Tablica ciągów do tabeli danych"},
            {"String Array To String"  ,  "Tablica ciągów do ciągu"},
            {"String To Clipboard"  ,  "Ciąg do schowka"},
            {"Clipboard To String"  ,  "Schowek na ciąg"},
            {"CSV To Data Table"  ,  "CSV do tabeli danych"},
            {"Data Table To CSV File"  ,  "Tabela danych do pliku CSV"},
            {"Citrix Activities"  ,  "Działania Citrix"},
            {"Focus Window Type"  ,  "Typ okna ostrości"},
            {"Image Click"  ,  "Kliknij obraz"},
            {"Image Double Click"  ,  "Obraz Kliknij dwukrotnie"},
            {"Image Right Click"  ,  "Obraz Kliknij prawym przyciskiem myszy"},
            {"Chrome Activities"  ,  "Działania Chrome"},
            {"Chrome Get HTML Content"  ,  "Chrome Pobierz zawartość HTML"},
            {"Chrome Mouse"  ,  "Mysz Chrome"},
            {"Chrome fire Event"  , "Zdarzenie Chrome fire"},
            {"Chrome Keyboard"  ,  "Klawiatura Chrome"},
            {"Chrome Miscellaneous"  ,  "Różne Chrome"},
            {"Chrome click At"  ,  "Chrome kliknij At"},
            {"Chrome drag And Drop To Object"  ,  "Chrom przeciągnij i upuść na obiekt"},
            {"Chrome edit Content"  ,  "Edytuj zawartość Chrome"},
            {"Chrome open"  ,  "Otwórz Chrome"},
            {"Chrome run Script"  ,  "Uruchom skrypt Chrome"},
            {"Chrome select"  ,  "Wybierz Chrome"},
            {"Chrome select Frame" , "Chrome wybierz Frame"},
            {"Chrome send Keys"  ,  "Chrome wysyłaj klucze"},
            {"Chrome submit"  ,  "Prześlij Chrome"},
            {"Chrome type"  ,  "Typ Chrome"},
            {"Chrome"  ,  "Chrom"},
            {"Mouse Activities"  ,  "Aktywność myszy"},
            {"Mouse"  ,  "Mysz"},
            {"Keyboard Activities"  ,  "Działania klawiatury"},
            {"Send Keys"  ,  "Wyślij klucze"},
            {"Activities"  ,  "Zajęcia"},
            { "Start" , "Początek" },
            { "WorkSpace" , "WorkSpace"}


        };
    }
}
