//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZappyChromeNativeConsole.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sapbydesign.com;")]
        public string SendXPATHTargets {
            get {
                return ((string)(this["SendXPATHTargets"]));
            }
            set {
                this["SendXPATHTargets"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sapbydesign.com|self^click2doubleclickoropen;")]
        public string RetryStrategies {
            get {
                return ((string)(this["RetryStrategies"]));
            }
            set {
                this["RetryStrategies"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sapbydesign.com;")]
        public string InsertPauseOnUrlChange {
            get {
                return ((string)(this["InsertPauseOnUrlChange"]));
            }
            set {
                this["InsertPauseOnUrlChange"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sapbydesign.com;")]
        public string RemoveSubmitCommand {
            get {
                return ((string)(this["RemoveSubmitCommand"]));
            }
            set {
                this["RemoveSubmitCommand"] = value;
            }
        }
    }
}
